---
- name: Configure nginx web server
  hosts: all 
  become: True
  tasks: 
  - name: install nginx on server
    apt:
      name: nginx
      state: latest 
  - name: start the server
    service:
      name: nginx
      state: started

- name: Configure httpd server
  hosts: all
  become: True
  tasks:
  - name: Install Apache2 package
    yum:
      name: httpd
      state: latest
  - name: Start server
    service:
      name: httpd
      state: started